export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export GOPATH=$HOME/.local/go
export GOBIN=$HOME/.local/go/bin
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export BAT_THEME=ansi
export PATH="$PATH:$HOME/.local/bin"
export EDITOR=nvim
export BROWSER=firefox
export GTK_USE_PORTAL=1
# export KWIN_TRIPLE_BUFFER=0
# export KWIN_DRM_DISABLE_TRIPLE_BUFFERING=1
# export KPIPEWIRE_FORCE_ENCODER=libx264
# export KWIN_LOG_PERFORMANCE_DATA=1
